// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// peel_cpp
List peel_cpp(NumericMatrix W, double lambda, double threshold);
RcppExport SEXP _ICONS_peel_cpp(SEXP WSEXP, SEXP lambdaSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(peel_cpp(W, lambda, threshold));
    return rcpp_result_gen;
END_RCPP
}
// detect_cpp
List detect_cpp(NumericMatrix W, double threshold, double lambda, int min_size, int max_k);
RcppExport SEXP _ICONS_detect_cpp(SEXP WSEXP, SEXP thresholdSEXP, SEXP lambdaSEXP, SEXP min_sizeSEXP, SEXP max_kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type W(WSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type min_size(min_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_k(max_kSEXP);
    rcpp_result_gen = Rcpp::wrap(detect_cpp(W, threshold, lambda, min_size, max_k));
    return rcpp_result_gen;
END_RCPP
}
// block_stats_cpp
List block_stats_cpp(NumericMatrix X, NumericVector center, IntegerVector g, int K);
RcppExport SEXP _ICONS_block_stats_cpp(SEXP XSEXP, SEXP centerSEXP, SEXP gSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type center(centerSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    rcpp_result_gen = Rcpp::wrap(block_stats_cpp(X, center, g, K));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ICONS_peel_cpp", (DL_FUNC) &_ICONS_peel_cpp, 3},
    {"_ICONS_detect_cpp", (DL_FUNC) &_ICONS_detect_cpp, 5},
    {"_ICONS_block_stats_cpp", (DL_FUNC) &_ICONS_block_stats_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_ICONS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
