# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.peel_cpp <- function(W, lambda, threshold) {
    .Call(`_ICONS_peel_cpp`, W, lambda, threshold)
}

.detect_cpp <- function(W, threshold, lambda, min_size, max_k) {
    .Call(`_ICONS_detect_cpp`, W, threshold, lambda, min_size, max_k)
}

.block_stats_cpp <- function(X, center, g, K) {
    .Call(`_ICONS_block_stats_cpp`, X, center, g, K)
}

